services:
  - type: web
    name: my-python-app
    env: python
    repo: https://github.com/Sivathekings/Pyro
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: main.py
    port: 8080
    envVars:
      - key: API_ID
        value: 14486797
      - key: API_HASH
        value: bf3b9df595c63aab3052f43fe1939068
      - key: BOT_TOKEN
        value: 5461167123:AAH2zJ3UQLYLPid0IzrAhf_0f20uEycWO3o
